Add UML for Exit Feature
AY2122S2-CS2103T-T12-3/tp pull request #104
Opened 2022-03-25 20:05 UTC by kevinkuo0320

Add exit feature into developer guide 
- activity diagram
- sequence diagram

2022-03-26 06:57 UTC, cwq2326 requested changes
I think you are using the wrong circle for the end point in the activity diagram and the font size of exit can be same as the rest. 

Otherwise, all looks good.

2022-03-27 14:13 UTC, jiale-c approved these changes
NICE! LGTM.

2022-03-27 14:13 UTC, jiale-c commented on docs/UserGuide.md
> +This is a sample screenshot of what you can expect from the `help` command.
LGTM!

2022-03-27 14:14 UTC, cwq2326 approved these changes

2022-03-27 14:14 UTC, merged